### PR TITLE
Renaming Dockerfile.ci to Dockerfile

### PR DESCRIPTION
**Pull request by thapakazi**
#### Changes made:
- rename  ̶D̶o̶c̶k̶e̶r̶f̶i̶l̶e̶.̶c̶i̶  > Dockerfile
- added readme

@bnaysakya 
We need to create a build trigger on dockerhub/cloudfactory, as I don't have enough permission to create one using the projects from cloudfactory repos. So I forked and created a build using this repo.. long way to  serve the purpose. @kajisaap

### CODE REVIEW

**Comment by kajisaap** [comment]
Not sure why we are forking the repository here(although that's also fine as this is a public repository). Is branch based PR not working for this?

**Comment by kajisaap** [comment]
I thought I gave you owner role in DockerHub. I think you have already setup the automated builds - Great!!!

Can you change something, though? Can you change source repo to cloudfactory/jruby please!
screen shot 2017-12-12 at 10 30 41 am

**Comment by thapakazi** [comment]
I afraid, I can't do that. So need to circumvent the drill.
 
Crazy permission there(@dockerhub) I have, I can create projects there but I can't  automated builds using cloudfactory repos :neckbeard:

**Comment by kajisaap** [comment]
Okay, I will delete yours and put company's repo there then. How about this PR vs https://github.com/cloudfactory/jruby/pull/2 ? I couldn't directly contribute to yours as you did not do branch based PR - don't know why?

**Pull request closed without merging**
